In [25]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [26]:
class MyLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight = nn.Parameter(torch.normal(0, 1, size=(in_features, out_features)), requires_grad=True)
        self.bias = nn.Parameter(torch.zeros(out_features), requires_grad=True)
    
    def forward(self, X):
        X = torch.matmul(X, self.weight) + self.bias
        return F.relu(X)

In [29]:
X = torch.randn((2, 4))
linear = MyLinear(4, 2)
net = nn.Sequential(nn.Linear(4, 4), MyLinear(4, 2))
net.add_module('linear3', nn.Linear(2,2))
Y = net(X).sum()
Y.backward()
for name, parameter in net.named_parameters():
    print(name)
    print(parameter)

0.weight
Parameter containing:
tensor([[-0.3029, -0.3045,  0.0876, -0.2961],
        [-0.0731, -0.1994,  0.4533,  0.3864],
        [-0.0198, -0.3556,  0.1820, -0.4715],
        [ 0.2560, -0.1573, -0.3486, -0.1724]], requires_grad=True)
0.bias
Parameter containing:
tensor([ 0.4821, -0.4918, -0.4103, -0.1729], requires_grad=True)
1.weight
Parameter containing:
tensor([[-1.2699, -0.6160],
        [ 0.3675,  0.5463],
        [-0.8753,  1.0485],
        [ 1.0848,  0.4043]], requires_grad=True)
1.bias
Parameter containing:
tensor([0., 0.], requires_grad=True)
linear3.weight
Parameter containing:
tensor([[ 0.0378, -0.3278],
        [ 0.6380,  0.4654]], requires_grad=True)
linear3.bias
Parameter containing:
tensor([-0.0418, -0.0626], requires_grad=True)
